### ISSUE TITLE
Multiple measures

### ISSUE THREAD

**Issue by kmicklas** [AhoyISki/AnyRope#1]
First off thanks for making this! I was kind of shocked to not easily find any crate with this data structure, and even had the idea to fork Ropey to make it.

One very useful feature of Ropey is that it maintains multiple measures (bytes, chars, lines, even UTF-16 code points) and you can navigate by any of them. For some use cases I have in mind for this data structure, I'd need something similar. Would you be open to adding that?

**Comment by kmicklas** [comment]
To be concrete, I think the way to support this is to make the measure function return an arbitrary monoidal type, and provide indexing functions that take a predicate with an appropriate monotonicity condition. There can still be helper methods that provide a straightforward indexing API for measures which are further partially ordered (probably most of them).

**Comment by AhoyISki** [comment]
Sorry for not replying to this sooner. Do you mean something like this?
```rust
pub trait Measurable {
    type Argument;

    fn measure(&self, arg: Self::Argument) -> usize;
}
```

**Comment by kmicklas** [comment]
Not exactly, it would be more like this:

```rust
pub trait Measurable {
    type Measure: Default + Add<Self::Measure, Output = Self::Measure>;

    fn measure(&self) -> Self::Measure;
}
```

As an example, for a text rope like Ropey, you could have a `Measure` like this:

```rust
struct TextMeasure {
    bytes: usize;
    chars: usize;
    utf16_code_points: usize,
    lines: usize
}
```

Even though this library is based on Ropey, it seems like with the current `usize`-only measure, it's not possible to reimplement a text rope with all the various indexing methods of Ropey.

**Comment by AhoyISki** [comment]
> Even though this library is based on Ropey, it seems like with the current `usize`-only measure, it's not possible to reimplement a text rope with all the various indexing methods of Ropey.

I mean, the point of this crate isn't really to be able to replicate Ropey, but I might add this feature, since it seems like a useful generalization of the capabilities of AnyRope.

**Comment by kmicklas** [comment]
Yeah, if I just needed those I'd use Ropey. 😄

To give an example, the measures I'd like to use  are the numbers of different types of delimiters (e.g. `()[]{}`) in a sequence of tokens for a programming language.

**Comment by AhoyISki** [comment]
So..., I've implemented the changes in this issue, and the API now looks like this:

```rust
pub trait FallibleOrd {
    fn fallible_cmp(&self, other: &Self) -> Ordering;
}

pub trait Measurable: Clone + Copy + PartialEq + Eq {
    type Measure: Debug
        + Default
        + Clone
        + Copy
        + PartialEq
        + Eq
        + Add<Output = Self::Measure>
        + Sub<Output = Self::Measure>
        + FallibleOrd;

    fn measure(&self) -> Self::Measure;
}
```

Now, operations dealing with querying, iterating in specific places, or modifying a rope will also require a comparison function, for example:

```rust
rope.insert(
    /* Measurable::Measure (insertion position) */,
    /* Measurable (inserted value) */,
    /* Fn(&Measurable::Measure, &Measurable::Measure) -> Ordering */
)
```

Now, for example, if you have a measure composed of a byte, char, and line values, you could pass something like `MyMeasure::char_cmp` to compare only chars, and ignore the other values.

There is also a new trait that must be implemented: `FallibleOrd`. This trait must be implemented by the `Measurable::Measure` type, in order to give it a "default comparison function". This function is not like the derivable `Ord` and `PartialOrd`, as it is supposed to be able to panic. It should panic whenever there is any ambiguity about a comparison, like one value being greater, while another is lower.
It needs to panic because this function is only meant to be used internally, where comparisons need to be unbiased, and give equal priority to all values in the struct, differently from `Ord` and `PartialOrd`, which create a hierarchy in order to always have a valid value.
If it panics, it means there is something wrong with any-rope, and that should be reported.

The `default` value for the `Measurable::Measure` struct is supposed to be the "0" value of it, that is, the minimum possible value that it could have. That also implies that, for any 2 given measures $m_1$ and $m_2$, $m_1 + m_2 \ge m_1, m_2$ and $m_{default} \le m_1 - m_2 \le m_1, m_2$. If that is not the case, then there would be multiple positions in the rope corresponding to the same measure, rendering the whole thing useless.
In debug mode, you will be warned if a value lower than the `default` one is used (some of the time), but that is not done in release mode, so be careful with that.

If this is what this issue was requesting, you can mark it as fixed.

(P.s. Never use the `fallible_cmp` function as the argument in a rope's method, it will almost definitely result in a panic).

**Comment by AhoyISki** [comment]
So far, there are no tests written with this new feature in mind, so there might be bugs with it (I think that's unlikely though).

**Comment by AhoyISki** [comment]
I'm gonna mark it as fixed, because to me, it seems fixed

**Comment by kmicklas** [comment]
Thank you! This is exactly what I was looking for.
